name: Build and Run
on:
  #push:
  #  branches:
  #    - main  # Change this to your main branch
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'azure resource group name'
        required: true
        default: 'demoGroup'
      region:
        description: 'azure region'
        required: true
        default: 'east us'
      subscriptionId:
        description: 'azure subscription id'
        required: true
      storageAccountName:
        description: 'storage account name'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.4  # Change this to your desired Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools

    - name: Build Python Package
      run: pip install --editable ./create_azstorage

    - name: Output Input Variables
      run: |
        echo "resourceGroupName: ${{ github.event.inputs.resourceGroupName }}"
        echo "region: ${{ github.event.inputs.region }}"
        echo "subscriptionId: ${{ github.event.inputs.subscriptionId }}"
        echo "storageAccountName: ${{ github.event.inputs.storageAccountName }}"
    
    - name: List Files
      run: tree

    - name: List Files
      run: |
        which create_azstorage_cli
        
    - name: Run python command
      run: |
        create_azstorage_cli \
          --resource-group-name ${{ github.event.inputs.resourceGroupName }} \
          --region ${{ github.event.inputs.region }} \
          --subscription-id ${{ github.event.inputs.subscriptionId }} \
          --storage-account-name ${{ github.event.inputs.storageAccountName }}
        
      

